#!/bin/bash
source ~/scripts/.env


# --- CONFIG ---
DEVICE_IP=$TV_IP
VOLUME_DOWN_AFTER_TIME="23"
VOLUME_DOWN_UNTIL_TIME="11"
VOLUME_DOWN_UNDER_VOL="75"
MORING_AFTER_TIME="6"
MORING_BEFORE_TIME="11"
# --- END OF CONFIG ---


# --- FUNCS ---
log() {
    local LEVEL=$1
    shift
    local DATE=$(date +'%Y-%m-%d %H:%M:%S')
    echo "[$DATE] [$LEVEL] $*"
}

tv_is_on() {
    timeout 2 adb connect "$DEVICE_IP" >/dev/null 2>&1
    state=$(timeout 2 adb -s "$DEVICE_IP" shell dumpsys display 2>/dev/null | grep 'mState=' | cut -d'=' -f2)
    [[ "$state" == "ON" ]]
}



# --- CHECK IF DEVICE WAS ONLINE AT THE START OF THE SCRIPT ---
WAS_ONLINE=0
if tv_is_on; then
    log INFO "ONLINE at script start."
    WAS_ONLINE=1
else
    log INFO "OFFLINE at script start."
    WAS_ONLINE=0
fi


# --- MAIN LOOP ---
while true; do
    # SET VOLUME DOWN FOR SET TIME
    CURRENT_HOUR=$(date +%-H)
    CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1 | tr -d '%')
    if (( (CURRENT_HOUR >= VOLUME_DOWN_AFTER_TIME || CURRENT_HOUR <= VOLUME_DOWN_UNTIL_TIME) && CURRENT_VOLUME > VOLUME_DOWN_UNDER_VOL )); then
        pactl set-sink-volume @DEFAULT_SINK@ "$VOLUME_DOWN_UNDER_VOL%"
        timeout 5 catt -d $DEVICE_IP volume 40
        $SPEAK "it's getting late, turning volume down"
    fi

    # DEVICE STATUS CHANGE AFFECTS
    if tv_is_on; then
        log INFO "Device online, WAS_ONLINE=$WAS_ONLINE"

        ## IF WASNT ONLINE AND SPOTIFY NOT PLAYING
        if [[ $WAS_ONLINE -eq 0 ]];then
            if [[ "$(sleep 5; playerctl -p spotify status 2>/dev/null)" != "Playing" ]]; then
                # IF MORNING: RUN MORNING COMMANDS
                if (( CURRENT_HOUR >= MORING_AFTER_TIME && CURRENT_HOUR <= MORING_BEFORE_TIME )); then
                    log INFO "Running MORNING commands..."
                    # --- MORNING COMMANDS ---
                    bash ~/scripts/max/max "wake up (from max/check-if-home)"
                else
                    log INFO "Running WELCOME commands..."
                    # --- WELCOME COMMANDS ---
                    bash ~/scripts/max/max "im home (from max/check-if-home)"
                fi
            else
                log INFO "Did not run commands - spotify playing."
            fi
        fi

        WAS_ONLINE=1

    # TV IS OFF
    else
        log INFO "Device offline, WAS_ONLINE=$WAS_ONLINE"
        if [[ $WAS_ONLINE -eq 1 ]]; then
            log INFO "Running OFFLINE commands..."
            # --- OFFLINE COMMANDS ---
            node ~/scripts/tuya-control/remote.js led off
            node ~/scripts/tuya-control/remote.js pluh-1 off
            node ~/scripts/tuya-control/remote.js pluh-2 off
            node ~/scripts/tuya-control/remote.js pluh-2 on
            node ~/scripts/tuya-control/remote.js bulb-1 off
            node ~/scripts/tuya-control/remote.js bulb-2 off

            WAS_ONLINE=0
        fi
    fi

    sleep 1

done

