#!/bin/bash

# --- COLORS ---
GREEN="\e[32m"
RED="\e[31m"
YELLOW="\e[33m"
GRAY="\e[90m"
NC="\e[0m"

# --- SETTINGS ---
LISTEN_MODE=0
LAST_COMMAND_TIME=0
CURRENT_VOLUME=""
LISTEN_VOLUME=-30%
TIMEOUT=30
export VOSK_LOG_LEVEL=-1
TV="192.168.1.4"
LOG_FILE="/tmp/max.log"

source ~/scripts/.env

# --- LOGGING ---
log() {
    local COLOR_NAME=$1
    shift
    local DATE=$(date +'%Y-%m-%d %H:%M:%S')
    local PRE_LOG="${GRAY}[$DATE]${NC} "
    if [[ "$COLOR_NAME" == "RED" ]]; then
        PRE_LOG="${GRAY}[$(date +'%H:%M:%S')]${NC} "
    fi
    local COLOR="${!COLOR_NAME}"
    local INPUT=$*
    echo -e "$PRE_LOG${COLOR}$INPUT${NC}" | tee -a "$LOG_FILE"
}


# --- BACKGROUND SCRIPTS ---
## CHECK IF HOME
CHECK_IF_HOME_SCRIPT="/home/$USER/scripts/max/check-if-home"
if ! pgrep -fx "bash $CHECK_IF_HOME_SCRIPT" >/dev/null; then
    bash "$CHECK_IF_HOME_SCRIPT" >/dev/null 2>&1 &
fi
## ALARMS
ALARMS_SCRIPT="/home/$USER/scripts/max/alarms"
if ! pgrep -fx "bash $ALARMS_SCRIPT" >/dev/null; then
    bash "$ALARMS_SCRIPT" >/dev/null 2>&1 &
fi


# --- THE MAX ---
echo " 🤖 | Max:"
echo "───────────"
log NC "Max started."
handle_command() {
    local cmd="$1"

    # --- SKIP SKISO WORDS ---
    if [[ "$cmd" =~ ^(huh|the|okay|you\'re welcome)$ || "$cmd" == *"yes sir"* || "$cmd" == *"wait"* ]]; then
        return
    fi

    # --- WAKE WORDS ---
    wake_words="(max|hi max|lex|rex)"
    if [[ "$cmd" =~ ^$wake_words\ .+ ]]; then
        LISTEN_MODE=1
        LAST_COMMAND_TIME=$(date +%s)
        CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
        pactl set-sink-volume @DEFAULT_SINK@ $LISTEN_VOLUME
        log GREEN "Listening..."
    elif [[ "$cmd" =~ ^$wake_words$ ]]; then
        LISTEN_MODE=1
        LAST_COMMAND_TIME=$(date +%s)
        CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
        pactl set-sink-volume @DEFAULT_SINK@ $LISTEN_VOLUME
        log GREEN "Listening..."
        $SPEAK "yes sir?"
        return 0
    fi

    # --- SHOW HEARD COMMANDS ---
    if [[ $LISTEN_MODE -eq 0 ]]; then
        log RED "$cmd"
        return 0
    fi

    # --- TIMEOUT CHECK ---
    local now=$(date +%s)
    if (( now - LAST_COMMAND_TIME > TIMEOUT )); then
        LISTEN_MODE=0
        log YELLOW "Timeout. Exiting..."
        $SPEAK "timeout"
        pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
        return 0
    fi
    LAST_COMMAND_TIME=$now

    # --- EXIT WORD ---
    if [[ "$cmd" == *"thanks"* || "$cmd" == *"thank you"* || "$cmd" == *"nothing"* || "$cmd" == *"never mind"* ]]; then
        LISTEN_MODE=0
        log GREEN "Exiting..."
        $SPEAK "you're welcome"
        pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
        return 0
    fi

    # --- COMMANDS ---
    case "$cmd" in
        # --- SPOTIFY ---
        *"play"*)
            log GREEN "Playing music..."
            $SPEAK "playing" &
            playerctl play
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        *"pause"*|*"stop"*|*"shut up"*)
            log GREEN "Stopping playback..."
            $SPEAK "okay" &
            playerctl stop
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        *"skip"*|*"skin"*)
            log GREEN "Skipping..."
            $SPEAK "okay" &
            playerctl next
            ;;
        *"volume up"*)
            log GREEN "Turning volume up..."
            $SPEAK "turning volume up" &
            pactl set-sink-volume @DEFAULT_SINK@ +25%
            CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
            LISTEN_MODE=0
            return 0
            ;;
        *"volume down"*)
            log GREEN "Turning volume down..."
            $SPEAK "turning volume down" &
            pactl set-sink-volume @DEFAULT_SINK@ -25%
            CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
            LISTEN_MODE=0
            return 0
            ;;
        *"reset"*|*"recent"*)
            log GREEN "Resetting volume..."
            $SPEAK "okay" &
            pactl set-sink-volume @DEFAULT_SINK@ 90%
            pactl set-sink-volume $(pactl list short sinks | awk '/hdmi/{print $2}') 100%
            playerctl volume 0.8 -p spotify
            catt -d $TV volume 40
            CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
            LISTEN_MODE=0
            return 0
            ;;
        "spotify"*)
            cmd="${cmd#* }"
echo "Heard: $cmd"
            s_query_result=$(bash ~/scripts/max/s-query "$cmd")
            log GREEN "Spotify: $s_query_result"
            $SPEAK "okay" &
            ;;

        # --- LIGHTS ---
        *"lights on"*)
            log GREEN "Turning on lights..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode scene purpleled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        *"lights off"*)
            log GREEN "Turning off lights..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 off
            node ~/scripts/tuya-control/remote.js bulb-2 off
            node ~/scripts/tuya-control/remote.js led off
            node ~/scripts/tuya-control/remote.js pluh-1 off
            node ~/scripts/tuya-control/remote.js pluh-2 off
            node ~/scripts/tuya-control/remote.js pluh-2 on
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        *"color red"*)
            log GREEN "Turning on red mode..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode color red
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode color red
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode color red
            node ~/scripts/tuya-control/remote.js pluh-1 off
            node ~/scripts/tuya-control/remote.js pluh-2 off
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        *"movie"*)
            log GREEN "Turning on movie mode..."
            $SPEAK "okay" &
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            playerctl stop
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode color magenta
            node ~/scripts/tuya-control/remote.js led off
            node ~/scripts/tuya-control/remote.js pluh-1 on
            node ~/scripts/tuya-control/remote.js pluh-2 on
            return 0
            ;;
        *"orange"*)
            log GREEN "Turning on orange mode..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode color orangebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode color orangebulb
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode color orangeled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            ;;
        *"ocean"*)
            log GREEN "Turning on ocean mode..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode color bluebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode color bluebulb
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode color blueled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            ;;
        *"hardcore"*)
            log GREEN "Turning on hardcore mode..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene hardcore
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene hardcore
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode scene hardcore
            node ~/scripts/tuya-control/remote.js pluh-1 on
            ;;
        *"disco"*)
            log GREEN "Turning on disco mode..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene disco
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene disco
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode scene disco
            node ~/scripts/tuya-control/remote.js pluh-1 on
            ;;
        *"white"*)
            log GREEN "Turning on white mode..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode white
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode white
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode color whiteled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            ;;
        *"seizure"*|*"flash"*|*"flesh"*)
            log GREEN "Turning on seizure mode..."
            $SPEAK "okay" &
            nohup node ~/scripts/tuya-control/remote.mjs >/dev/null 2>&1 &
            echo $! > /tmp/tuya-beat.pid
            ;;
        *"calm down"*)
            log GREEN "Turning off seizure mode..."
            $SPEAK "okay" &
            kill $(cat /tmp/tuya-beat.pid) && rm -rf /tmp/tuya-beat.pid
            ;;

        # --- CLI COMMANDS ---
        *"lockin"*)
            pactl set-sink-volume @DEFAULT_SINK@ 100%
            playerctl volume 0.8
            catt -d 192.168.1.4 volume 40
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode scene purpleled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            ;;
        *"sheleft"*)
            $SPEAK "she left" &
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene flash_red_pink
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene flash_red_pink
            sleep 5
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene purplebulb
            ;;

        # --- OTHER ---
        *"show bus"*|*"show boss"*)
            xfce4-terminal -e "bash ~/scripts/ksk/bus -b 24 -f Kadaka -a kodu"
            ;;
        *"kill"*)
            log GREEN "Killing kiosk..."
            $SPEAK "killing keyyawsk"
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            tmux kill-server
            ;;
        *"shut down"*|*"shot down"*|*"shut though"*|*"shot though"*)
            log GREEN "Shutting down..."
            $SPEAK "shutting down" &
            timeout 5 ssh t-pm "sudo ddcutil setvcp 0xD6 4 2>/dev/null"
            node ~/scripts/tuya-control/remote.js bulb-1 off
            node ~/scripts/tuya-control/remote.js bulb-2 off
            node ~/scripts/tuya-control/remote.js led off
            node ~/scripts/tuya-control/remote.js pluh-1 off
            node ~/scripts/tuya-control/remote.js pluh-2 off
            node ~/scripts/tuya-control/remote.js pluh-2 on
            playerctl stop -p spotify
            adb shell input keyevent KEYCODE_SLEEP
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        *"wake up")
            log GREEN "Good morning..."
            pactl set-sink-volume @DEFAULT_SINK@ 40%
            playerctl volume 0.7 -p spotify
            $SPEAK "good morning!"
            playerctl next -p spotify
            adb shell input keyevent KEYCODE_WAKEUP
            timeout 5 ssh t-pm "sudo ddcutil setvcp 0xD6 1 2>/dev/null"
            timeout 5 catt -d $DEVICE_IP volume 40
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode color orangebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode color orangebulb
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode color orangeled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            tmux kill-server
            ;;
        *"i'm home"*|*"i'm back"*|*"im home"*|*"im back"*)
            log GREEN "Welcome back..."
            pactl set-sink-volume @DEFAULT_SINK@ 100%
            playerctl volume 0.8 -p spotify
            $SPEAK "welcome back!"
            playerctl next -p spotify
            adb shell input keyevent KEYCODE_WAKEUP
            timeout 5 ssh t-pm "sudo ddcutil setvcp 0xD6 1 2>/dev/null"
            timeout 5 catt -d $DEVICE_IP volume 40
            node ~/scripts/tuya-control/remote.js bulb-1 on
            node ~/scripts/tuya-control/remote.js bulb-1 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js bulb-2 on
            node ~/scripts/tuya-control/remote.js bulb-2 mode scene purplebulb
            node ~/scripts/tuya-control/remote.js led on
            node ~/scripts/tuya-control/remote.js led mode scene purpleled
            node ~/scripts/tuya-control/remote.js pluh-1 on
            CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            tmux kill-server
            ;;
        *"project off"*|*"project of"*|*"projector off"*|*"projector of"*)
            log GREEN "Turing off projector..."
            $SPEAK "okay" &
            node ~/scripts/tuya-control/remote.js pluh-2 off
            node ~/scripts/tuya-control/remote.js pluh-2 on
            pactl set-sink-volume @DEFAULT_SINK@ "$CURRENT_VOLUME"
            LISTEN_MODE=0
            return 0
            ;;
        #"who"*|"what"*|"where"*|"when"*|"why"*|"how"*|"do"*|"does"*|"did"*|"is"*|"are"*|"am"*|"was"*|"were"*|"can"*|"could"*|"would"*|"will"*|"shall"*|"should"*|"has"*|"have"*|"had"*|"may"*|"might"*|"must"*)
        "question"*)
            log GREEN "Question received..."
            echo "AI thinking..."
            ai_answer=$(echo "answer with the least sentences possible: $cmd" | ollama run llama2)
            log GREEN "$ai_answer"
            $SPEAK "$ai_answer" &
            ;;
        *)
            log YELLOW "$cmd - Not a command."
            ;;
    esac
}



# --- RUN SINGLE COMMAND IF PROVIDED ---
if [[ -n "$1" ]]; then
    LISTEN_MODE=1
    LAST_COMMAND_TIME=$(date +%s)
    CURRENT_VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
    handle_command "$*"
    exit 0
fi



# --- MAIN LOOP ---
while read -r line; do
    if [[ "$line" == HEARD:* ]]; then
        command="${line#HEARD: }"

        # --- WORD COUNTER ---
        words=$(cat ~/scripts/auth/ksk.theword)
        matches=0
        for w in $words; do
            count_for_word=$(grep -o -i "\b$w\b" <<< "$command" | wc -l)
            ((matches+=count_for_word))
        done
        if (( matches > 0 )); then
            ((count+=matches))
            log GREEN "MONKEYS: $count"
            $SPEAK "[REMOVED]" &
        fi

        handle_command "$command"
    fi
done < <(python3 -u ~/scripts/max/mic-listener.py 2>/dev/null)
