#!/bin/bash
source ~/scripts/.env


# --- USAGE ---
declare -A DICT=(
    ["USAGE"]="bash $0 <song_query>"
    ["INFO"]="Spotify CLI search and play."
)
source <(curl -s vps.tihkel.ee/usage) DICT "$@"


# --- CHECK IF QUERY SET ---
if [ $# -lt 1 ]; then
    echo "ERROR: No query provided."
    exit 1
else
    query="$*"
fi


# --- GET SPOTIFY ACCESS TOKEN ---
TOKEN=$(
    curl -s -X POST "https://accounts.spotify.com/api/token" \
        -u "$SPOTIFY_CLIENT_ID:$SPOTIFY_CLIENT_SECRET" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=client_credentials" |
    jq -r '.access_token'
)
if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
    echo "ERROR: No spotify token received."
    exit 1
fi


# --- SEARCH TRACK ---
TRACK_JSON=$(
    curl -s -G "https://api.spotify.com/v1/search" \
        -H "Authorization: Bearer $TOKEN" \
        --data-urlencode "q=$query" \
        --data-urlencode "type=track" \
        --data-urlencode "limit=1"
)
TRACK_URI=$(echo "$TRACK_JSON" | jq -r '.tracks.items[0].uri // empty')
TRACK_NAME=$(echo "$TRACK_JSON" | jq -r '.tracks.items[0].name // empty')
TRACK_ARTIST=$(echo "$TRACK_JSON" | jq -r '.tracks.items[0].artists[0].name // empty')


# --- PLAY TRACK ---
if [[ -n "$TRACK_URI" ]]; then
    echo "Playing: '$TRACK_NAME' by '$TRACK_ARTIST'."
    playerctl --player=spotify open "$TRACK_URI"
    sleep 4
    xdotool mousemove 1900 1040 click 1
    sleep 4
    xdotool mousemove 1341 782 click 1
    xdotool key Alt+Tab
else
    echo "ERROR: Song not found for: '$query'"
    exit 1
fi
