#!/bin/bash


# --- CONFIG ---
## MAIN SINK
SINK_A=$(pactl list short sinks | grep hdmi-surround | awk '{print $2}')
## SECONDARY SINK
SINK_B=$(pactl list short sinks | grep GeneralPlus_USB_Audio_Device | awk '{print $2}')
DELAY_B=160


# --- LOGGING ---
log() {
    echo "[INFO] $*"
}
error() {
    echo "[ERROR] $*"
}


## --- CHECK IF SINKS WERE FOUND ---
if [ -z "$SINK_A" ] || [ -z "$SINK_B" ]; then
    error "One of the sinks was not found."
    exit 1
fi


# --- CONVERT MS to MICROSECONDS ---
DELAY_US=$(($DELAY_B * 1000))


# --- DISCOVERING SINKS FOR MORE DEPENDANT CONNECTION ---
log "Waiting for PulseAudio sinks..."
while ! pactl list short sinks | grep -q "$SINK_A"; do sleep 1; done
while ! pactl list short sinks | grep -q "$SINK_B"; do sleep 1; done
log "Sinks found."


# --- KILL ALL PREVIOUS ATTEMPTS (sinks) ---
pactl unload-module module-null-sink 2>/dev/null
pactl unload-module module-loopback 2>/dev/null
pactl unload-module module-ladspa-sink 2>/dev/null
pactl unload-module module-combine-sink 2>/dev/null


# --- CREATE CUSTOM COMBINED SINK ---
COMBINED=$(pactl load-module module-null-sink sink_name=COMB channels=6 sink_properties=device.description="Combined_Output")


# --- ADD BOTH LOOP DEVICES TO COMBINED SINK ---
LOOP_A=$(pactl load-module module-loopback source=COMB.monitor sink="$SINK_A" latency_msec=0)
LOOP_B=$(pactl load-module module-loopback source=COMB.monitor sink="$SINK_B" latency_msec=$DELAY_B)


# --- MAKE COMBINED SINK AS THE DEFAULT OUTPUT ---
log "Running COMBINED SINK as deafault output..."
pactl set-default-sink COMB

