#!/bin/bash

# --- START CHECK IF HOME (if not already) ---
if ! pgrep -f "bash ~/scripts/max/check-if-home" >/dev/null 2>&1; then
    bash ~/scripts/max/check-if-home >/dev/null 2>&1 &
fi

# --- KILL LAST AND CREATE NEW SESSION ---
trap cleanup EXIT
cleanup() { pkill -P $$; }
tmux kill-server >/dev/null 2>&1
sleep 0.2
SESSION="kiosk"

# --- VERTICAL LINES ---
# LINE0
tmux new-session -d -s "$SESSION" 'watch -ctn1 bash ~/scripts/ksk/c-playing'
pane0=$(tmux list-panes -t "$SESSION" -F "#{pane_id}" | head -n1)
# LINE1
tmux select-layout -t "$SESSION" even-vertical >/dev/null 2>&1
tmux split-window -v -t "$pane0" 'watch -ctn120 bash ~/scripts/ksk/mycal'
pane1=$(tmux display-message -p "#{pane_id}")
# LINE2
tmux select-layout -t "$SESSION" even-vertical >/dev/null 2>&1
tmux split-window -v -t "$pane1" 'bash ~/scripts/ksk/ssh-auth'
pane2=$(tmux display-message -p "#{pane_id}")
# LINE3
tmux select-layout -t "$SESSION" even-vertical >/dev/null 2>&1
tmux split-window -v -t "$pane2" 'bash ~/scripts/ksk/timers'
pane3=$(tmux display-message -p "#{pane_id}")
# LINE4
tmux select-layout -t "$SESSION" even-vertical >/dev/null 2>&1
tmux split-window -v -t "$pane3" 'cava'
pane4=$(tmux display-message -p "#{pane_id}")
# SET EQUAL SPACING
tmux select-layout -t "$SESSION" even-vertical
# --- HORISONTAL SPLIT PANES ---
# | FOR LINE2
# PANE5
cmd_pane5='watch -ctn1 "w | grep -v tmux | awk '\''NR>1 {printf \"%-7s %-6s %-14s %-6s %-6s %-0s\n\",\$1,\$2,\$3,\$4,\$5,\$8}'\''"'
tmux split-window -h -t "$pane1" "$cmd_pane5"
pane5=$(tmux display-message -p "#{pane_id}")
# PANE11
tmux split-window -h -t "$pane5" 'watch -ctn 10 bash ~/scripts/ksk/gmail && read'
pane11=$(tmux display-message -p "#{pane_id}")
# PANE10
#cmd_pane10='watch -ctn1 "w | grep -v tmux | awk '\''NR>1 {printf \"%-7s %-6s %-14s %-6s %-6s %-0s\n\",\$1,\$2,\$3,\$4,\$5,\$8}'\''"'
#tmux split-window -v -t "$pane5" "$cmd_pane10"
#pane10=$(tmux display-message -p "#{pane_id}")
# | FPR LINE3
# PANE6
tmux split-window -h -t "$pane2" 'tty-clock -cs -C 5'
pane6=$(tmux display-message -p "#{pane_id}")
# PANE7
ssh_ip=$(echo $SSH_CLIENT | awk '{print $1}')
if [[ "$ssh_ip" == 217.146.66.5 ]]; then
   tmux split-window -h -t "$pane6" 'bash ~/scripts/ksk/bus -b 13 -f Väike-Õismäe -a zone'
else
   tmux split-window -h -t "$pane6" 'bash ~/scripts/ksk/bus -b 13 -f Priisle -a kodu'
fi
pane7=$(tmux display-message -p "#{pane_id}")
(
  while true; do
    sleep 2
    for i in {1..8}; do
      tmux send-keys -t "$pane7" a
      tmux send-keys -t "$pane7" a
      tmux send-keys -t "$pane7" a
      tmux send-keys -t "$pane7" a
      sleep 1
    done
    sleep 1
    tmux send-keys -t "$pane7" q
  done
) &
pane7=$(tmux display-message -p "#{pane_id}")
# | FOR LINE4
# PANE8
tmux split-window -h -t "$pane3" 'bash ~/scripts/ksk/s-player'
pane8=$(tmux display-message -p "#{pane_id}")
# PANE9
tmux split-window -h -t "$pane8" 'bash ~/scripts/max/max'
pane9=$(tmux display-message -p "#{pane_id}")

# --- TMUX SETTINGS ---
tmux set-option -t "$SESSION" status off
tmux set-option -t kiosk pane-border-style 'fg=black'
tmux set-option -t kiosk pane-active-border-style 'fg=black'
tmux set-option -t "$SESSION" mouse on
tmux set-option -g display-panes-time 1
tmux bind-key -T root q kill-session

# --- TMUX RESIZE ---
# VERTICAL LINES
tmux resize-pane -t "$pane0" -y 3
tmux resize-pane -t "$pane1" -y 5
tmux resize-pane -t "$pane1" -x 20
tmux resize-pane -t "$pane2" -x 15
tmux resize-pane -t "$pane2" -y 8
tmux resize-pane -t "$pane3" -x 5
# HORISONTAL PANES
tmux resize-pane -t "$pane5" -y 4
tmux resize-pane -t "$pane6" -y 6
tmux resize-pane -t "$pane7" -x 20
tmux resize-pane -t "$pane8" -y 3
tmux resize-pane -t "$pane9" -x 20
tmux resize-pane -t "$pane11" -x 20

# --- SHOW/HIDE/MODIFY PANES WHEN SPOTIFY PLAYING ---
(
  hidden=false
  while true; do
    sleep 1
    status=$(playerctl -p spotify status 2>/dev/null)
    if [[ "$status" == "Playing" ]]; then
      if $hidden; then
        tmux resize-pane -t "$pane0" -y 6 2>/dev/null
        tmux resize-pane -t "$pane4" -y 6 2>/dev/null

        tmux resize-pane -t "$pane2" -y 8 2>/dev/null
        hidden=false
      fi
    else
      if ! $hidden; then
        tmux resize-pane -t "$pane0" -y 0 2>/dev/null
        tmux resize-pane -t "$pane4" -y 0 2>/dev/null

        tmux resize-pane -t "$pane2" -y 8 2>/dev/null
        hidden=true
      fi
    fi
  done
) &

# --- POST SETUP ---
#tmux kill-pane -t "$pane9"
# FIX/RESPAWN C-PLAYING AND TTY-CLOCK
(sleep 1;
tmux respawn-pane -k -t "$SESSION"."$pane0"
tmux respawn-pane -k -t "$SESSION"."$pane6"
tmux respawn-pane -k -t "$SESSION"."$pane8"
) &
# FOCUS ON PANE
tmux select-pane -t "$pane8"

# --- START SESSION ---
tmux attach-session -t "$SESSION"
