#!/bin/bash
bash <(curl -s dev.tihkel.ee/banner.id) "DISK"

main_fs="/dev/$(lsblk -no NAME -r -o NAME,MOUNTPOINT | awk '$2=="/"{print $1}')"
COLOR="\033[1;35m"
NC="\033[0m"

sudo echo && \
df -h | awk -v COLOR="$COLOR" -v NC="$NC" 'NR>1{if($6=="/"){printf COLOR"%-20s %10s / %-10s %4s"NC"\n", $6, $3, $2, $5}else{printf "%-20s %10s / %-10s %4s\n", $6, $3, $2, $5}}' | grep -v "snap" && \
echo && \
sudo fdisk -l $(lsblk -dn -o NAME | grep -E "^(sd|nvme|hd)" | awk '{print "/dev/" $1}') | awk -v main="$main_fs" -v COLOR="$COLOR" -v NC="$NC" 'NR>9{if($1==main){printf COLOR"%-20s %-10s %-10s"NC"\n", $1, $5, substr($0,index($0,$6))}else{printf "%-20s %-10s %-10s\n", $1, $5, substr($0,index($0,$6))}}' && \
echo
