#!/bin/bash

# --- USAGE ---
declare -A DICT=(
    ["USAGE"]="bash $0 <os_name> [args]"
    ["INFO"]="Grub-Boot script is a shortcut to boot into a different OS on the machine."
    ["-s"]="Shutdown and after next boot go into the selected OS."
    ["--list"]="List all OS found from grub."
)
source <(curl -s vps.tihkel.ee/usage) DICT "$@"


# --- LIST OS IF GIVEN ARG ---
GRUB_CONFIG=$(sudo cat /boot/grub/grub.cfg | grep -E "^menuentry|^submenu" | nl -v0)
if [[ " $@ " =~ " --list " ]]; then
    GRUB_CONFIG_LIST_OS=$(echo "$GRUB_CONFIG" | awk '{gsub(/["'\''"]/, "", $0); print $3, $4}')
    echo "$GRUB_CONFIG_LIST_OS"
    exit 0
else
    # --- FIND THE RESULTS ---
    KEYWORD="$1"
    GRUB_CONFIG_RESULT=$(echo "$GRUB_CONFIG" | grep -i "$KEYWORD")
    GRUB_CONFIG_RESULT_NAME=$(echo "$GRUB_CONFIG_RESULT" | awk '{gsub(/["'\''"]/, "", $0); print $3, $4}' | head -n1)
    GRUB_CONFIG_RESULT_NUM=$(echo "$GRUB_CONFIG_RESULT" | awk '{print $1}' | head -n1)
fi


# --- ASK CONFIRMATION INPUT ---
read -rp "Boot into '$GRUB_CONFIG_RESULT_NAME'? [y/N]: " CONFIRM
if [[ "$CONFIRM" == [yY] && "$GRUB_CONFIG_RESULT_NUM" != "" ]]; then
    # SET NEXT BOOT THE SELECTED OS
    sudo grub-reboot "$GRUB_CONFIG_RESULT_NUM"
    # SHUTDOWN IF ARG PROVIDED
    [[ " $* " =~ " -s " ]] && sudo shutdown now
    # OTHERWISE REBOOT
    sudo reboot
else
    echo "Aborting..."
fi
