#!/bin/bash


# --- USAGE ---
declare -A DICT=(
    ["USAGE"]="bash $0 [dir_paths]"
    ["INFO"]="Shows the system inodes and for Zone web hosting shows the limit."
)
source <(curl -s vps.tihkel.ee/usage) DICT "$@"


# --- COLORS ---
RED='\033[31m'
YELLOW='\033[33m'
GREEN='\033[32m'
BOLD='\033[1m'
NC='\033[0m'


# --- QUOTA COMMAND CHECK ---
quota_output=$(quota 2>/dev/null)
if [ $? -ne 0 ]; then
    echo -e "WARN: 'quota' command unavailable."
    echo
else
    used_inodes=$(echo "$quota_output" | awk 'NR==3 {print $5}')
    inode_limit=$(echo "$quota_output" | awk 'NR==3 {print $6}')
    inode_usage_percent=$(( used_inodes * 100 / inode_limit ))
    if [ "$inode_usage_percent" -ge 80 ]; then
        inode_usage_percent_color=$RED
    elif [ "$inode_usage_percent" -ge 50 ]; then
        inode_usage_percent_color=$YELLOW
    else
        inode_usage_percent_color=$GREEN
    fi
    echo
    echo -e "${BOLD}Inodes used:${NC} ${inode_usage_percent_color}${used_inodes}${NC} (limit: ${inode_limit}, $inode_usage_percent%)"
    echo
fi


# --- SHOW INODE USAGE ---
## INODE USAGE FUNC IN CURRENT DIR
inode_usage() {
    du -s $1* $1.* --inodes 2>/dev/null | sort -hr | head -n 10 | awk -v RED="$RED" -v YELLOW="$YELLOW" -v GREEN="$GREEN" -v NC="$NC" '{
        inodes = $1
        path = ""
        for (i = 2; i <= NF; i++) {
            if (path == "") path = $i
            else path = path " " $i
        }
        if (inodes >= 50000) color = RED
        else if (inodes >= 10000) color = YELLOW
        else color = GREEN
        printf "%s%7d%s %s\n", color, inodes, NC, path
    }'
    echo "$(du --inodes -s $1 2>/dev/null | awk '{printf "%7s %s\n", $1, $2}')"
#    echo "Total: $(du --inodes -s $1 2>/dev/null | awk '{printf $1}')"
    echo
}


## USAGE for ./domeenid
if [ -d "./domeenid" ] && ! [ $# -gt 0 ]; then
    WWWDOMAIN="$(ls ./domeenid | head -n 1)"
    WWWDOMAIN_PATH="./domeenid/$WWWDOMAIN/"
    echo -e "${BOLD}$WWWDOMAIN_PATH${NC}"
    inode_usage $WWWDOMAIN_PATH
fi

## USAGE FOR CURRENT/SET PATH
if [ $# -gt 0 ]; then
    for set_path in "$@"; do
        [[ "$set_path" != /* && "$set_path" != ./* ]] && set_path="./$set_path"
        [[ "$set_path" != */ ]] && set_path="$set_path/"

        echo -e "${BOLD}$set_path${NC}"
        inode_usage "$set_path"
    done
else
    echo -e "${BOLD}./${NC}"
    inode_usage ./
fi


