#!/bin/bash

input="$1"
domain=${input#http*://}; domain=${domain%%/*}; domain=${domain,,}


# --- USAGE ---
## MISSING REQUIRED ARG
if [ -z "$domain" ]; then
    echo "ERROR: Target missing."
    echo
    echo "Usage:"
    echo "  bash $0 <domain_or_ip> [args]"
    exit 1
fi

# ARGUMENT USAGE MANAGER
declare -A DICT=(
    ["USAGE"]="bash $0 <domain_or_ip> [args]"
    ["INFO"]="Script meant for domain/IP scan that primarily digs DNS records and site status with request status codes. Includes extra CMS checking from the sites HTML code. Does also include subdomain and port scanning with custom CMS checks (WP users, Site+Home URL etc.)"
    ["-f"]="Runs full scan including: \n - custom CMS scans \n - subdomain search \n - nmap port scan"
)
source <(curl -s vps.tihkel.ee/usage) DICT "$@"
clear


# --- COLORS ---
RED="\e[31m"
GREEN="\e[32m"
PURPLE="\e[35m"
BLUE="\e[36m"
YELLOW="\e[93m"
GRAY="\e[90m"
BOLD="\e[1m"
NC="\e[0m"


# --- DOMAIN SCAN ---
echo -e "${GRAY}Domain: ${PURPLE}$domain${NC}"
echo


# ---DIG DNS ---
ns_dns=$(dig +short $domain NS)
ip=$(dig +short "$domain" A)
mx_dns=$(dig +short $domain MX)
spf_dns=$(dig +short $domain TXT | grep "v=spf1" | sed 's/" "//g; s/"//g')
dmarc_dns=$(dig +short _dmarc.$domain TXT)
txt_dns=$(dig +short $domain TXT | grep -v "v=spf1" | sed 's/" "//g; s/"//g')

# CNAME
hosts=("k2._domainkey" "k3._domainkey" "web" "blue.smly._domainkey" "green.smly._domainkey" "dev" "vpn" "www" "api" "mail" "blog" "shop")
cname_found=""
for host in "${hosts[@]}"; do
    result=$(dig +short CNAME "${host}.${domain}")
    if [[ -n "$result" ]]; then
        cname_found+="${GRAY}[${BLUE}${host}.$domain${GRAY}]: ${result}${NC}\n"
    fi
done

# DKIM
declare -A DKIM_HOSTS=(
    ["ZONE"]="zone._domainkey"
    ["ELKDATA"]="mail-out._domainkey"
    ["GOOGLE"]="google._domainkey"
    ["ZOHO"]="zmail._domainkey"
    ["selector1"]="selector1._domainkey"
    ["selector2"]="selector2._domainkey"
    ["ZPANEL"]="default._domainkey"
    ["ICLOUD"]="icloud._domainkey"
    ["DIRECTO"]="directo._domainkey"
    ["MAILCHIMP_mte1"]="mte1._domainkey"
    ["MAILCHIMP_mte2"]="mte2._domainkey"
    ["EXCELLENT"]="smtp4._domainkey"
    ["RESEND/AMAZONSES"]="resend._domainkey"
    ["ZENDESK_1"]="zendesk1._domainkey"
    ["ZENDESK_2"]="zendesk2._domainkey"
    ["MANDRILL"]="mandrill._domainkey"
    ["s1"]="s1._domainkey"
    ["s2"]="s2._domainkey"
)
dkim_found=""
for provider in "${!DKIM_HOSTS[@]}"; do
    selector="${DKIM_HOSTS[$provider]}"
    result=$(dig +short TXT "${selector}.${domain}" | sed 's/" "//g; s/"//g')
    if [[ -n "$result" ]]; then
        dkim_found+="${GRAY}[${BLUE}${provider}${GRAY}] ${result}${NC}\n"
    fi
done


echo -e "${BOLD}${PURPLE}   WEB   ${GRAY}"
echo -e "${BOLD}${PURPLE}──═━┈━═──${NC}"


# --- SITE ---
check_site() {
    local proto=$1
    status_code=$(timeout 3 curl -s -L --max-time 10 -o /dev/null -w "%{http_code}" "$proto://$domain")
    if [[ "$status_code" =~ ^[234] ]]; then
        echo "$proto"
    fi
}
protocol=$(check_site https)
protocol=${protocol:-$(check_site http)}

## CREATE THE FINAL URL
get_final_url=$(timeout 3 curl -s -o /dev/null -w "%{http_code} %{url_effective}" -L "http://$domain" | awk '$1 ~ /^(2|3|4)/ {print $2}')
meta_redirect=$(timeout 3 curl -s "http://$domain" | grep -i '<meta http-equiv="refresh"' | grep -oP 'url=\K[^"]+')
if [[ -n "$meta_redirect" ]]; then
    get_final_url="$meta_redirect"
fi
# IF SERVER DOES NOT HAVE HTTP OPEN
http_off=false
if [[ -z "$get_final_url" ]]; then
    http_off=true
    get_final_url=$(timeout 3 curl -s -o /dev/null -w "%{http_code} %{url_effective}" -L "https://$domain" | awk '$1 ~ /^(2|3|417)/ {print $2}')
fi
final_url_rem_slash="${get_final_url%/}"
final_url="$(
if [[ "$final_url_rem_slash" == https://* ]]; then
    echo -e "${BLUE}HTTPS://${final_url_rem_slash#https://}${GRAY}"
else
    echo -e "${RED}HTTP${BLUE}://${final_url_rem_slash#http://}${GRAY}"
fi
)"
declare -A http_codes=(
  [000]="Site Down"
  [200]="OK"
  [301]="Moved Permanently"
  [308]="Permanent Redirect"
  [400]="Bad Request"
  [401]="Unauthorized"
  [403]="Forbidden"
  [404]="Not Found"
  [409]="Conflict"
  [421]="Misdirected Request"
  [417]="Expectation Failed"
  [418]="I’m a teapot"
  [500]="Internal Server Error"
  [503]="Service Unavailable"
)
site_status_code=$(timeout 3 curl -s -H "Expect:" -o /dev/null -w "%{http_code}" -L "$protocol://$domain")
#site_status_code=$(curl -s -H "Expect:" -o /dev/null -w "%{http_code}" -L "http://$domain")

site_status=$(
if [[ "$site_status_code" == "200" ]]; then
    echo -e "${GREEN}$site_status_code ${GRAY}(${GREEN}${http_codes[$site_status_code]}${GRAY})${GRAY}"
elif [[ "$site_status_code" == "301" || "$site_status_code" == "308" ]]; then
    ### SSL CERT PROBBLEM CHECK
    timeout 3 curl -IL "$final_url_rem_slash" >/dev/null 2>&1
    curl_exit=$?
    if [ $curl_exit -eq 60 ]; then
        failed_status_curl="SSL cert problem"
    elif [ $curl_exit -ne 0 ]; then
        failed_status_curl="Connection failed: $curl_exit"
    else
        failed_status_curl="idk"
    fi
    echo -e "${RED}$site_status_code ${GRAY}(${RED}${http_codes[$site_status_code]}${GRAY}) - ${RED}$failed_status_curl${GRAY}"
else
    echo -e "${RED}$site_status_code ${GRAY}(${RED}${http_codes[$site_status_code]:-Unknown}${GRAY})${GRAY}"
fi
)

extra_info=""
### IF SITE IS UP
if [ -n "$protocol" ]; then
    if [ $http_off == true ]; then
        extra_info+="(${RED}HTTP is turned OFF${GRAY}) "
    else
        ### NO REDIRECT TO HTTPS CHECK
        if [[ "$final_url_rem_slash" == http://* ]]; then
            extra_info+="(${RED}HTTP${GRAY}) "
        fi
    fi
    ### REDIRECT CHECK
    if [[ "${final_url_rem_slash#http*://}" == "www.$domain" ]]; then
        extra_info+="(${YELLOW}REDIRECT${GRAY} to ${BLUE}WWW${GRAY}) "
    elif [[ "${final_url_rem_slash#http*://}" != "$domain" ]]; then
        extra_info+="(${YELLOW}REDIRECT${GRAY} to ${BLUE}${final_url_rem_slash#http*://}${GRAY}) "
    fi
    ### BLANK PAGE CHECK
    if [[ "$(timeout 3 curl -sL --max-time 10 "$protocol://$domain" | wc -c)" -eq 0 ]] && [[ "$site_status_code" != "301" && "$site_status_code" != "308" ]]; then
        extra_info+="(${RED}BLANK PAGE${GRAY}) "
    fi
fi
echo -e "${PURPLE} SITE ${GRAY} $extra_info$site_status"
echo -e "${PURPLE}──────${GRAY}"

## CMS
if [ -n "$protocol" ]; then
    headers=$(timeout 3 curl -sI "$protocol://$domain" | tr -d '\000')
    html=$(timeout 3 curl -sL --max-time 10 "$protocol://$domain" | tr -d '\000')
    declare -A cms_patterns=(
        ["WordPress"]="wp-includes"
        ["Joomla"]="Joomla!"
        ["Drupal"]="Drupal"
        ["Shopify"]="Shopify"
        ["Magento"]="Magento"
        ["Prestashop"]="prestashop"
        ["TYPO3"]="TYPO3"
        ["Squarespace"]="Squarespace"
        ["Wix"]="Wix.com"
        ["Voog"]="voog.com"
        ["GoDaddy Website Builder"]="website-builder-data-prod"
        ["GoDaddy Website Builder"]="Go Daddy Website Builder"
        ["Google Hosted"]="lh3.googleusercontent.com"
        ["SiteBuilder (Site.pro)"]="wb_element"
        ["Default Hosting Page ?"]="construction"
        ["Default Domain Page"]="Your domain has been registered but"
        ["Dept Suspension"]="The maintainer of the website can review their outstanding obligations in the Control Panel."
        ["Veebimajutus.ee"]="veebimajutus\.ee"
    )
    found=false
    found_cms=""
    for cms in "${!cms_patterns[@]}"; do
        if echo "$html" | grep -qi "${cms_patterns[$cms]}"; then
            echo -e "${GREEN}$cms${GRAY}"
            found=true
            found_cms="$cms"
            break
        fi
    done
#        if [[ "$found" != true && "$extra_info" =~ BLANK\ PAGE ]]; then
        if ! $found && ! [[ "$extra_info" =~ "BLANK PAGE" ]]; then
            echo -e "${YELLOW}Unknown CMS${GRAY}"
            score=0
            score_goal=30
            hit() {
                local regex="$1"
                local points="$2"
                local name="$3"
                if echo "$html" | grep -Eiq "$regex"; then
                    echo -e "  [+] $name detected +$points"
                    ((score+=points))
                fi
            }
            hit "<section" 10 "section tag"
            hit "<article" 10 "article tag"
            hit "<nav" 10 "nav tag"
            hit "/assets/|/static/|/src/|/dist/" 20 "custom asset directories"
            hit "app\\.js|main\\.js|bundle\\.js" 10 "JS bundle files"
            hit "[a-z]+__[a-z]+|[a-z]+--[a-z]+" 15 "BEM CSS classes"
            hit "\\.min\\.js|\\.min\\.css" 5 "minified CSS/JS"
            hit "/api/|/graphql" 20 "API endpoints"
            hit "favicon\.ico|favicon\.png|icon-.*\.png" 5 "custom favicon"
            hit "data-reactroot|id=\"app\"|ng-app" 15 "SPA frontend framework"
            if (( score >= score_goal )); then
                echo -e "${GREEN}self-made: ($score/$score_goal)${GRAY}"
            else
                echo -e "${RED}not self-made?: ($score/$score_goal)${GRAY}"
            fi
        fi
        ## SERVER INFO
        server=$(echo "$headers" | grep -i "^Server:" | cut -d' ' -f2-)
        [ -n "$server" ] && echo -e "${GRAY}Server: $server${NC}"
#    fi
    echo
fi


# --- NS ---
echo -e "${PURPLE} NS ${NC}$([ -n "$ns_dns" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}────${BLUE}"
if [ -n "$ns_dns" ]; then
    echo  "$ns_dns"
    echo
fi


# --- A ---
echo -e "${PURPLE} A ${NC}$([ -n "$ip" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}───${GRAY}"
if [ -n "$ip" ]; then
    ptr=$(host "$(echo "$ip" | head -n 1)" | grep -i "pointer" | awk '{print $5}')
#    sleep 1
    netname=$(whois "$(echo "$ip" | tail -n 1)" 2>/dev/null | grep -i netname | cut -d: -f2 | xargs)
    country=$(whois "$(echo "$ip" | tail -n 1)" 2>/dev/null | grep -i country | tail -n 1 | cut -d: -f2 | xargs)
    if [ -z "$netname" ]; then
        netname="${YELLOW}unknown"
    else
        ### KNOWN IP CHECKS
        if [[ "$ip" == "217.146.70.51" ]]; then
            netname="${GREEN}Zone URL record"
        elif [[ "$ip" == "185.31.240.240" ]]; then
            netname="${GREEN}Default Domain Page"
        elif [[ "$ip" == "212.123.41.108" ]]; then
            netname="${RED}ICANN Contact Verify Page"
        elif [[ "$ip" == "85.222.234.14" ]]; then
            netname="${BLUE}EE-ZONE-UVN-VOOG"
        fi
        ### KNOWN COUNTRY CHECKS
        if [[ "$country" != "EE" ]]; then
            country=" ${GRAY}(${RED}$country${GRAY})"
        else
            country=""
        fi

    fi
    echo -e "$ip (${BLUE}$netname${GRAY})$country $ptr"
    echo
fi


# --- CNAME ---
echo -e "${PURPLE} CNAME ${NC}$([ -n "$cname_found" ] && echo -e "${GREEN}+${NC}" || echo -e "${RED}-${NC}")"
echo -e "${PURPLE}───────${NC}"
if [ -n "$cname_found" ]; then
    echo -e "$cname_found"
fi


echo
echo -e "${BOLD}${PURPLE}  EMAIL  ${GRAY}$([ -n "$ns_dns" ] && [ -n "$mx_dns" ] && [ -n "$spf_dns" ] && [ -n "$dkim_found" ] && [ -n "$dmarc_dns" ] && echo -e "${GREEN}+${NC}" || echo "${RED}-${NC}")"
echo -e "${BOLD}${PURPLE}──═━┈━═──${NC}"


# --- MX ---
echo -e "${PURPLE} MX ${NC}$([ -n "$mx_dns" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}────${GRAY}"
if [ -n "$mx_dns" ]; then
    while read -r PRIORITY HOST; do
        echo -e "${PRIORITY} ${BLUE}${HOST}${GRAY}"
    done <<< "$mx_dns"
    echo
fi


# --- SPF ---
echo -e "${PURPLE} SPF ${NC}$([ -n "$spf_dns" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}─────${GRAY}"
if [ -n "$spf_dns" ]; then
    for word in $spf_dns; do
        if [[ "$word" == include:* ]]; then
            prefix="include:"
            spf_domain="${word#include:}"
            echo -e "${prefix}${BLUE}${spf_domain}${GRAY} "
        else
            echo -e "$word "
        fi
    done
    echo
fi


# --- DKIM ---
echo -e "${PURPLE} DKIM ${NC}$([ -n "$dkim_found" ] && echo -e "${GREEN}+${NC}" || echo -e "${RED}-${NC}")"
echo -e "${PURPLE}──────${NC}"
if [ -n "$dkim_found" ]; then
    echo -e "$dkim_found"
fi


# --- DMARC ---
echo -e "${PURPLE} DMARC ${NC}$([ -n "$dmarc_dns" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}───────${GRAY}"
if [ -n "$dmarc_dns" ]; then
    echo "$dmarc_dns"
    echo
fi


echo
echo -e "${BOLD}${PURPLE}  OTHER  ${GRAY}"
echo -e "${BOLD}${PURPLE}──═━┈━═──${NC}"


# --- TXT ---
echo -e "${PURPLE} TXT ${NC}$([ -n "$txt_dns" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}─────${GRAY}"
if [ -n "$txt_dns" ]; then
    echo "$txt_dns"
    echo
fi


# === START OF -f (FULL SCAN) ===
if [[ " $@ " =~ " -f " ]]; then


# --- CMS BASED SCANNING ---
## WORDPRESS
if [[ "$cms" == "WordPress" ]]; then
    wp_json=$(timeout 3 curl -sL "$domain/wp-json")

    wp_version=$(curl -sL "$domain" | grep -oP '(?<=content="WordPress )[^"]+')
    site_and_home_url=$(echo "$wp_json" | jq '{url,home}')
    wp_users=$(curl -sL "$domain/wp-json/wp/v2/users" | jq '.[] | {id, name}')
    xmlrpc_status=$(curl -sI https://tihkel.ee/xmlrpc.php | head -n1 | awk '{print $2}')
fi
echo -e "${PURPLE} CMS SCAN ${NC}$([ -n "$site_and_home_url" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}──────────${GRAY}"
if [[ "$cms" == "WordPress" ]]; then
    ## WP VERSION
    if [[ -n "$wp_version" ]]; then
        echo -e "Version: $wp_version"
    else
        echo -e "${RED}WP version not found.${GRAY}"
    fi
    ## XMLRPC
    if [[ "$xmlrpc_status" == "200" ]]; then
        echo -e "xmlrpc.php: ${GREEN}$xmlrpc_status${GRAY}"
    else
        echo -e "xmlrpc.php: ${RED}$xmlrpc_status${GRAY}"
    fi
    ## WP SITE+HOME URLS
    if [[ -n "$site_and_home_url" ]]; then
        echo -e "$site_and_home_url"
    else
        echo -e "${RED}Site and Home URL's not found.${GRAY}"
    fi
    ## WP USERS
    if [[ -n "$wp_users" ]]; then
        echo -e "$wp_users"
    else
        echo -e "${RED}No users found."
    fi
    echo
fi


# --- SUBDOMAINS ---
# crt.sh
ct=$(timeout 5 curl -s "https://crt.sh/?q=%25.$domain&output=json" 2>/dev/null | \
    grep -oP '"name_value":"\K[^"]+' | sed 's/\\n/\n/g;s/\*\.//g')
# HackerTarget
ht=$(timeout 5 curl -s "https://api.hackertarget.com/hostsearch/?q=$domain" 2>/dev/null | \
    cut -d',' -f1)
# RapidDNS (no key, good coverage)
rd=$(timeout 5 curl -s "https://rapiddns.io/subdomain/$domain?full=1&down=1" 2>/dev/null | \
    grep -oP '(?<=<td>)[a-z0-9._-]+\.'$domain'(?=</td>)')
subdomains=$(echo -e "$ct\n$ht\n$rd" | sed 's/\*\.//g' | sort -u | grep "\.$domain$")
#subdomains=$(timeout 3 curl -s "https://crt.sh/?q=%25.$domain&output=json" | \
#    grep -oP '"name_value":"\K[^"]+' | \
#    sed 's/\\n/\n/g' | \
#    sed 's/\*\.//g' | \
#    sort -u | \
#    grep "\.$domain$")
echo -e "${PURPLE} SUBDOMAINS ${NC}$([ -n "$subdomains" ] && echo -e ${GREEN}+${GRAY} || echo -e ${RED}-${GRAY})"
echo -e "${PURPLE}────────────${GRAY}"
if [ -n "$subdomains" ]; then
    for sub in $subdomains; do
        sub_http_off=false
        sub_http_off_info=""
        # PING CHECK
        if ping -c1 -W1 "$sub" &>/dev/null; then
            # GET FINAL URL + STATUS CODE
            read -r sub_code redirect <<< "$(timeout 3 curl -s -o /dev/null -w "%{http_code} %{url_effective}" -L --max-time 10 "http://$sub")"
            # IF HTTP OFF - TRY HTTPS
            if [ "$sub_code" == "000" ]; then
                sub_http_off=true
                read -r sub_code redirect <<< "$(timeout 3 curl -s -o /dev/null -w "%{http_code} %{url_effective}" -L --max-time 10 "https://$sub")"
                redirect=""
            fi
            clean_redirect="${redirect%/}"
            redirect_info=""
            # STATUS INFO
            if [ "$sub_code" == "000" ]; then
                sub_http_off=false
                sub="${GRAY}$sub${GRAY}"
                redirect_info=""
                code_info="(${RED}${sub_code} ${http_codes[$sub_code]}${GRAY})"
            elif [ "$sub_code" == "200" ]; then
                code_info="(${GREEN}${sub_code} ${http_codes[$sub_code]}${GRAY})"
            elif [[ "$sub_code" == "301" || "$sub_code" == "308" ]]; then
                timeout 3 curl -IL "https://$sub" >/dev/null 2>&1
                curl_exit=$?
                if [ $curl_exit -eq 60 ]; then
                    failed_status_curl="SSL cert problem"
                elif [ $curl_exit -ne 0 ]; then
                    failed_status_curl="Connection failed: $curl_exit"
                else
                    failed_status_curl=""
                fi
                code_info="(${RED}${sub_code} ${http_codes[$sub_code]:-Unknown}${GRAY}) - ${RED}$failed_status_curl${GRAY}"
            else
                code_info="(${RED}${sub_code} ${http_codes[$sub_code]:-Unknown}${GRAY})"
            fi
            # REDIRECT DETECT
            if [[ -n "$redirect" && "$clean_redirect" != "http://$sub" && "$clean_redirect" != "https://$sub" ]]; then
                if [[ "$clean_redirect" == https://* ]]; then
                    proto="${YELLOW}https"
                else
                    proto="${RED}HTTP${YELLOW}"
                fi
                sub="${YELLOW}$sub${GRAY}"
                target="${clean_redirect#http*://}"
                redirect_info=" $proto://$target"
            fi
        else
            sub="${GRAY}$sub${GRAY}"
            redirect_info=" is down (ping failed)"
            code_info=""
        fi
        if [ $sub_http_off == true ];then
            sub_http_off_info="${GRAY}(${RED}HTTP is turned OFF${GRAY})${GRAY}"
        fi
        echo -e "[${GREEN}$sub${GRAY}]$redirect_info${GRAY} $code_info $sub_http_off_info"
    done
    echo
fi


# --- PORTS ---
echo -e "${PURPLE} PORTS ${NC}"
echo -e "${PURPLE}───────${GRAY}"
#timeout --signal=INT 10 nmap -sV "$domain" 2>/dev/null | grep -E '^[0-9]+/(tcp|udp)' | awk '{print $1 " - " $3}'
nmap -sV "$domain" -v | grep -oP '\d+(?=/tcp)'
#timeout 10 nmap -sV "$domain" -v | grep -oP '\d+(?=/tcp)'
echo


# === END OF -f ===
exit 1
fi
